id = "applescript"
name = "AppleScript"
version = "1.8.5"
schema_version = 1
authors = ["Helge Sverre <helge.sverre@gmail.com>"]
description = "AppleScript language support for Zed"
repository = "https://github.com/HelgeSverre/zed-applescript"

[grammars.applescript]
repository = "https://github.com/HelgeSverre/tree-sitter-applescript"
commit = "b523b13e7ca0fc8f70df9972928d7c86055c6aca"
